get:
  summary: Say hello application
  description: |
    A simple example for integrating with an application-restricted service, using an OAuth 2.0 client_credentials grant type.
    
    Any authorised request to this endpoint initiates a 'Hello Application' response.
  tags:
    - open-api-example-microservice
  parameters:
    - $ref: './parameters/accept_header.yaml#/components/parameters/acceptHeader'
  responses:
    200:
      description: "OK"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: the message contents
          example:
            $ref: "./examples/success/hello_application.json"
    401:
      description: "Unauthorised"
      content:
        application/json:
          schema:
            $ref: "./schemas/missing_credentials.json"
          example:
            $ref: "./examples/errors/missing_credentials.json"
  security:
    - applicationRestricted: []