
openapi: "3.0.3"

info:
  title: Identity Verification Questions
  description: "Identity Verification Questions is a service that confirms a user's identity and provides differing levels of authentication.\n\n### What is this API for?\nIdentity Verification Questions currently only contains one endpoint, which is used to update the outcome of a user's voice ID attempt.\nWhen an API changes in a way that is backwards-incompatible, we increase the version number of the API. \nSee our [reference guide](/api-documentation/docs/reference-guide#versioning) for more on\nversioning.\nWe use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:\n* 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action\n* 400 to 499 if it failed because of a client error by your application\n* 500 to 599 if it failed because of an error on our server\n\nErrors specific to each API are shown in the Endpoints section, under Response. \nSee our [reference guide](/api-documentation/docs/reference-guide#errors) for more on errors.\nYou can use the sandbox environment to\n[test this API](https://developer.service.hmrc.gov.uk/api-documentation/docs/testing)."
  contact: {}
  version: '1.0'
servers:
  - url: https://api.service.hmrc.gov.uk/
    variables: {}
security:
  - userRestricted:
      - identity-verification-questions
paths:
  /identity-verification-questions/questions:
    post:
      tags:
        - identity-verification-questions
      summary: Get questions a set of identifiers
      description: Get questions and a correlation id for a set of identifiers.
      operationId: Postivqquestion
      parameters:
        - name: callback-reference
          in: path
          description: The reference ID of the call, which has been both Base64-encoded and URL-encoded. The URL-decoded ID must have a maximum length of 30 characters.
          required: true
          style: simple
          schema:
            type: string
            example: dGhpcyBpcyBhbiBleGFtcGxlIGlk
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/questions/nino'
                - $ref: '#/components/schemas/questions/sautr'
                - $ref: '#/components/schemas/questions/payRef'
                - example:
                    status: Y
                    description: VB pass
            examples:
              success:
                description: Successful voice biometrics verification
                value:
                  status: Y
                  description: VB pass
        required: true
      responses:
        '200':
          description: 'Returns a correlation id, along with a (possibly empty) set of questions for the identifiers given'
          headers: {}
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/questions'
                  - description : JSON schema validation success
                    example:
                      code: INVALID_JSON_BODY
              example:
                code: INVALID_JSON_BODY

        '403':
          description: 'You are not authorized to use the question repository'
          headers: {}
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - description: JSON schema validation failure
                    example:
                      code: INVALID_JSON_BODY
              example:
                code: INVALID_JSON_BODY
      deprecated: false
  /identity-verification-questions/answers:
    post:
      tags:
        - identity-verification-questions
      summary: check answers for given questions with a set of identifiers
      description: Send a correlation id and identifier selection, along with answer data for each question from the user
      operationId: Postivqquestion
      parameters:
        - name: callback-reference
          in: path
          description: The reference ID of the call, which has been both Base64-encoded and URL-encoded. The URL-decoded ID must have a maximum length of 30 characters.
          required: true
          style: simple
          schema:
            type: string
            example: dGhpcyBpcyBhbiBleGFtcGxlIGlk
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/IdentityVerificationVoiceBiometricsChallengeResultrequest'
                - example:
                    status: Y
                    description: VB pass
            examples:
              success:
                description: Successful voice biometrics verification
                value:
                  status: Y
                  description: VB pass
        required: true
      responses:
        '200':
          description: 'The outcome of the answer check, indicating a correct or incorrect response'
          headers: {}
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/answers'
                  - description : JSON schema validation success
                    example:
                      code: INVALID_JSON_BODY
              example:
                code: INVALID_JSON_BODY
        '403':
          description: 'You are not authorized to use the question repository'
          headers: {}
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - description: JSON schema validation failure
                    example:
                      code: INVALID_JSON_BODY
              example:
                code: INVALID_JSON_BODY
        '404':
          description: 'The supplied correlation id and selection did not match any known questions'
          headers: {}
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - description: JSON schema validation failure
                    example:
                      code: INVALID_JSON_BODY
              example:
                code: INVALID_JSON_BODY
      deprecated: false

components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            identity-verification-questions: the identity verification questions user
  schemas:
    errorResponse:
      title: errorResponse
      required:
        - code
      type: object
      properties:
        code:
          type: string
    questions:
      title: questions
      type: object
      properties:
        nino:
          type: string
          description: The NINO associated with the cred id
        sautr:
          type: string
          description: The sautr associated with the cred id
        payRef:
          type: object
          description: This is the reference associated with the cred id that consists of the tax office number and tax office reference
          required:
            - taxOfficeNumber
            - taxOfficeReference
          properties:
            taxOfficeNumber:
              type: string
            taxOfficeReference:
              type: string
    answers:
      title: answers
      required:
        - correlationId
        - answers
      type: object
      properties:
        correlationId:
          type: string
          description: The correlationId associated with the stored answers ivq
        selection:
          type: object
          description: The identifier to be used to select the questions/answers evidence sources that will be check
          properties:
            nino:
              type: string
              description: The NINO associated with the cred id
            sautr:
              type: string
              description: The sautr associated with the cred id
            payRef:
              type: object
              description: This is the reference associated with the cred id that consists of the tax office number and tax office reference
              required:
                - taxOfficeNumber
                - taxOfficeReference
              properties:
                taxOfficeNumber:
                  type: string
                taxOfficeReference:
                  type: string
        answers:
          type: object
          description: The answers with the associated question key to be checked against the data sources
          properties:
            questionKey:
              type: string
              description: The question key relating to the question
            answer:
              type: string
              description: The answer relating to the question
        ivJourney:
          type: object
          description: the iv journey object passed from the identity verification microservice for metrics
          properties:
            journeyId:
              type: string
            journeyType:
              type: string
            authProviderId:
              type: string
            origin:
              type: string
tags:
  - name: identity-verification-questions
    description: ''
        
